framework:
  workflows:
    checkout_process:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - App\Entity\ShoppingCart
      initial_marking:
        - shopping
      places:
        - shopping
        - shopping_cart
        - delivery_address
        - summary
        - ordered
      transitions:
        to_shopping:
            from: [shopping, shopping_cart, delivery_address, summary, ordered]
            to: shopping
        to_shopping_cart:
            from: [shopping, shopping_cart, delivery_address, summary, ordered]
            to: shopping_cart
        to_delivery_address:
            from: [shopping_cart, delivery_address]
            to: delivery_address
        to_summary:
            from: [delivery_address, summary]
            to: summary
        to_ordered:
            from: [summary, ordered]
            to: ordered
